gpu_id: 0
multi_gpus: True
num_workers: 4
seed: 666
exp_name: 'nextqa_result'

train:
  lr: 0.0002
  batch_size: 64 
  restore: False
  max_epochs: 60
  word_dim: 300
  motion_dim: 1024
  appearance_dim: 1536 
  module_dim: 512
  glove: True


val:
  flag: True

test:
  test_num: 0
  write_preds: True

dataset:
  name: 'next-qa'
  question_type: 'none'
  data_dir: './data/NEXT-QA/'
  save_dir: './result_nextqa/'
  appearance_feat: './data/NEXT-QA/next-qa_appearance_feat_orign.h5'
  train_question_pt: './data/NEXT-QA/next-qa_train_questions.pt'
  val_question_pt: './data/NEXT-QA/next-qa_val_questions.pt'
  vocab_json: './data/NEXT-QA/next-qa_vocab.json'
